# Generated by Django 3.2.5 on 2021-08-12 12:47

from django.db import migrations, models
import django.db.models.deletion
import onipkg_contrib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('thumbnail', models.ImageField(blank=True, help_text='Dimensões: 960x540; Tam. Máx.: 300kb; Somente os formatos .jpeg, .jpg e .png são permitidos.', null=True, upload_to='courses/thumbnails/', validators=[onipkg_contrib.validators.validate_image_format, onipkg_contrib.validators.validate_image_max_300], verbose_name='Thumbnail do Curso')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Curso')),
                ('categories', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('YT', 'Youtube'), ('DS', 'Dsps')], default='IG', max_length=2, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Curso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Curso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.coursesection', verbose_name='Seção desta aula')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100, verbose_name='Título do Vídeo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('vimeo_video_id', models.CharField(help_text='ID do vídeo que será embedado.', max_length=150, verbose_name='ID do vídeo no Vimeo')),
                ('video_length', models.SmallIntegerField(verbose_name='Duração do vídeo (em minutos')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.lecture', verbose_name='Aula Relacionada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Título do Arquivo')),
                ('file', models.FileField(blank=True, help_text='You can upload any documents you wish here', null=True, upload_to='courses/files', validators=[onipkg_contrib.validators.validate_file_max_10000, onipkg_contrib.validators.validate_document_format], verbose_name='Arquivo')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.lecture', verbose_name='Aula Relacionada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
