# Generated by Django 3.2.5 on 2021-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_course_coursesection_lecture_sectionfile_sectionvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledgebase.post',),
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Seção do Curso', 'verbose_name_plural': 'Seções dos Cursos'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='sectionfile',
            options={'verbose_name': 'Arquivo de Aula', 'verbose_name_plural': 'Arquivos de Aula'},
        ),
        migrations.AlterModelOptions(
            name='sectionvideo',
            options={'verbose_name': 'Vídeo de Aula', 'verbose_name_plural': 'Vídeos de Aula'},
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('TU', 'Tutorial'), ('BL', 'Blog')], default='BL', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome da Seção'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome da Aula'),
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
