# Generated by Django 3.2.5 on 2021-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_auto_20210914_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='sectionfile',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='sectionvideo',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delatado'),
        ),
    ]
