# Generated by Django 3.2.5 on 2021-10-21 16:48

from django.db import migrations, models
import tutor.apps.contrib.validators
import tutor.apps.knowledgebase.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_auto_20210924_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=1, help_text='Dimensões: 960x540; Tam. Máx.: 300kb; Somente os formatos .jpeg, .jpg e .png são permitidos.', upload_to=tutor.apps.knowledgebase.models.base.course_thumbnail_directory, validators=[tutor.apps.contrib.validators.validate_image_format, tutor.apps.contrib.validators.validate_image_max_300], verbose_name='Thumbnail do Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default=1, help_text='Dimensões: 960x540; Tam. Máx.: 300kb; Somente os formatos .jpeg, .jpg e .png são permitidos.', upload_to=tutor.apps.knowledgebase.models.base.post_image_directory, validators=[tutor.apps.contrib.validators.validate_image_format, tutor.apps.contrib.validators.validate_image_max_300], verbose_name='Imagem Destaque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionfile',
            name='file',
            field=models.FileField(default=1, help_text='You can upload any documents you wish here', upload_to=tutor.apps.knowledgebase.models.base.lecture_file_thumbnail_directory, validators=[tutor.apps.contrib.validators.validate_file_max_10000, tutor.apps.contrib.validators.validate_document_format], verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='featured_image',
            field=models.ImageField(default=1, help_text='Dimensões: 960x540; Tam. Máx.: 300kb; Somente os formatos .jpeg, .jpg e .png são permitidos.', upload_to=tutor.apps.knowledgebase.models.base.post_image_directory, validators=[tutor.apps.contrib.validators.validate_image_format, tutor.apps.contrib.validators.validate_image_max_300], verbose_name='Imagem Destaque'),
            preserve_default=False,
        ),
    ]
