# Generated by Django 3.2.5 on 2021-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_alter_sectionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='sectionfile',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='sectionvideo',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado'),
        ),
    ]
