# Generated by Django 3.2.5 on 2021-11-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_auto_20211118_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Post do Blog', 'verbose_name_plural': 'Posts do Blog'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-id'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
    ]
