# Generated by Django 3.2.5 on 2022-02-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_auto_20211123_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seção do Curso', 'verbose_name_plural': 'Seções dos Cursos'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post do Blog', 'verbose_name_plural': 'Posts do Blog'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Categoria de Post', 'verbose_name_plural': 'Categorias de Post'},
        ),
        migrations.AlterModelOptions(
            name='sectionfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arquivo de Aula', 'verbose_name_plural': 'Arquivos de Aula'},
        ),
        migrations.AlterModelOptions(
            name='sectionvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vídeo de Aula', 'verbose_name_plural': 'Vídeos de Aula'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
    ]
