# Generated by Django 3.2.5 on 2022-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_auto_20220217_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('YT', 'Youtube'), ('DS', 'Dsps'), ('CR', 'Carrer'), ('MB', 'Music Business'), ('CP', 'Copyright'), ('MM', 'Music Marketing')], default='IG', max_length=2, verbose_name='Categoria'),
        ),
    ]
