# Generated by Django 3.2.5 on 2022-07-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0012_alter_course_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['id'], 'verbose_name': 'Seção do Curso', 'verbose_name_plural': 'Seções dos Cursos'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['id'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='sectionfile',
            options={'ordering': ['id'], 'verbose_name': 'Arquivo de Aula', 'verbose_name_plural': 'Arquivos de Aula'},
        ),
        migrations.AlterModelOptions(
            name='sectionvideo',
            options={'ordering': ['id'], 'verbose_name': 'Vídeo de Aula', 'verbose_name_plural': 'Vídeos de Aula'},
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.coursesection', verbose_name='Seção desta aula'),
        ),
        migrations.AlterField(
            model_name='sectionfile',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.lecture', verbose_name='Aula Relacionada'),
        ),
        migrations.AlterField(
            model_name='sectionvideo',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.lecture', verbose_name='Aula Relacionada'),
        ),
    ]
