# Generated by Django 4.1.5 on 2023-04-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0013_auto_20220721_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('YT', 'Youtube'), ('DS', 'Dsps'), ('CR', 'Carrer'), ('MB', 'Music Business'), ('CP', 'Copyright'), ('MM', 'Music Marketing')], default='IG', max_length=2, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='UserTutorialRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False, help_text='Se for marcado, este objeto será apagado do banco de dados', verbose_name='Deletado')),
                ('user_id', models.PositiveIntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.tutorial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
