# Generated by Django 4.1.5 on 2023-10-17 14:24

from django.db import migrations, models
import knowledgebase.models.base
import onipkg_contrib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0014_alter_course_categories_usertutorialread'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_landscape',
            field=models.ImageField(blank=True, help_text='Dimensões: 1080x566; Tam. Máx.: 5mb; Somente os formatos .jpeg, .jpg e .png são permitidos.', null=True, upload_to=knowledgebase.models.base.course_thumbnail_directory, validators=[onipkg_contrib.validators.validate_image_format, onipkg_contrib.validators.validate_file_max_5000], verbose_name='Thumbnail Paisagem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(help_text='Dimensões: 1280x1280; Tam. Máx.: 5mb; Somente os formatos .jpeg, .jpg e .png são permitidos.', upload_to=knowledgebase.models.base.course_thumbnail_directory, validators=[onipkg_contrib.validators.validate_image_format, onipkg_contrib.validators.validate_file_max_5000], verbose_name='Thumbnail Quadrada'),
        ),
    ]
